-- AlterTable
ALTER TABLE "workout" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "workout_exercise" ADD COLUMN     "level" INTEGER,
ADD COLUMN     "reps" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "set" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "weight" DOUBLE PRECISION;
